name: Code coverage

on:
  push:
    branches:
      - main
  pull_request:

env:
  COVERAGE: 0

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

      - name: Install dependencies
        run: uv sync

      - name: Code Coverage
        run: |
          uv run coverage run -m pytest -vv
          uv run coverage report --omit=tests/\*
          COVERAGE_PERCENT=$(uv run coverage report | awk 'END{print $4}')
          COVERAGE=${COVERAGE_PERCENT%\%}
          echo "COVERAGE=$COVERAGE" >> "$GITHUB_ENV"

      - name: Coverage Check
        run: |
          if (( $(echo "$COVERAGE < 80" | awk '{print ($1 < 80)}' ) )); then
            echo "Code coverage is $COVERAGE% and below expected level"
            exit 1
          else
            echo "Sufficient code coverage"
          fi
