name: Code coverage

on:
  push:
    branches:
      - main
  pull_request:

env:
  COVERAGE: 0

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt -r requirements.txt

      - name: Code Coverage
        run: |
          coverage run -m pytest -vv
          coverage report --omit=tests/\*
          COVERAGE_PERCENT=$(coverage report | awk 'END{print $4}')
          COVERAGE=${COVERAGE_PERCENT%\%}
          echo "COVERAGE=$COVERAGE" >> "$GITHUB_ENV"

      - name: Coverage Check
        run: |
          if (( $(echo "$COVERAGE < 80" | awk '{print ($1 < 80)}' ) )); then
            echo "Code coverage is $COVERAGE% and below expected level"
            exit 1
          else
            echo "Sufficient code coverage"
          fi
