name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  COVERAGE: 0

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
          cache-dependency-path: 'eodhp-utils/*.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements.txt

      - name: Run tests
        run: pytest ./tests -vv

      - name: Code Coverage
        run: |
          coverage run -m pytest
          echo COVERAGE_PERCENT=$(coverage report | awk 'END{print $4}') >> "$GITHUB_ENV"
          echo COVERAGE=${COVERAGE_PERCENT%\%} >> "$GITHUB_ENV"
          echo $COVERAGE

      - name: Coverage Check
        run: |
          if (( $(echo "$COVERAGE < 200" | bc -l ) )); then
            echo "Code coverage is $COVERAGE% and below expected level"
            exit 1
          else
            echo "Sufficient code coverage"
          fi
          

#      - name: Coverage Check
#        if: $COVERAGE < 100
#        uses: actions/github-script@v3
#        with:
#          script: |
#              core.setFailed('Not enough code coverage')
          

#      - name: Code Coverage Report
#        uses: irongut/CodeCoverageSummary@v1.3.0
#        with:
#          filename: coverage/**/coverage.cobertura.xml
#          badge: true
#          fail_below_min: true
#          format: markdown
#          hide_branch_rate: false
#          hide_complexity: true
#          indicators: true
#          output: both
#          thresholds: "60 80"
